name: alquran_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_compass: any  # Gunakan "any" jika tidak ada versi spesifik
  animated_text_kit: ^4.2.1 
  shared_preferences: ^2.0.13
  image_picker: ^0.8.4+4
  get: ^4.6.6
  audioplayers: any  # Gunakan "any" jika tidak ada versi spesifik
  cached_network_image: ^3.4.1
  permission_handler: ^11.3.1
  flutter_launcher_icons: ^0.9.2
  another_flushbar: ^1.12.30
  table_calendar: ^3.1.2
  animations: ^2.0.0
  flutter_qiblah: ^3.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/kereem.png
    - /Users/rizkicahya/alquran_app/assets/images/Alhamdulillah.png
    - /Users/rizkicahya/alquran_app/assets/images/Allahuakbar.png
    - /Users/rizkicahya/alquran_app/assets/images/Subhanallah.png
    - /Users/rizkicahya/alquran_app/assets/images/Lailahaillallah.png
    - /Users/rizkicahya/alquran_app/assets/images/masjid-2.png
    - /Users/rizkicahya/alquran_app/assets/images/background.png
    - /Users/rizkicahya/alquran_app/assets/logo/kereem-1.png
    - /Users/rizkicahya/alquran_app/assets/images/kompas-2.png
    - /Users/rizkicahya/alquran_app/assets/images/arrow.png

    - /Users/rizkicahya/alquran_app/assets/logo/tasbih.png
    - /Users/rizkicahya/alquran_app/assets/logo/quran.png
    - /Users/rizkicahya/alquran_app/assets/logo/quran-iqro.png

    - /Users/rizkicahya/alquran_app/assets/profile/profile_cat.png
    - /Users/rizkicahya/alquran_app/assets/profile/profile_dog.png
    - /Users/rizkicahya/alquran_app/assets/profile/profile_goat.png

    - assets/cityOfIndonesia.json



flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/kereem.png"  # Path logo aplikasi
